# -*- coding: utf-8 -*-
"""yartseva "mini_project_02_csv.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SDpHrDflni5hf2RmF_c9qV0ekIMPQNUR

# **Завдання: Чому впали продажі освітніх курсів?**

Ваша компанія займається продажем онлайн-курсів з програмування. Курси продаються протягом усього року. У вас є синтетичні дані про продажі за 2 роки — з січня 2023 по травень 2025.

Останнім часом менеджмент занепокоєний: у травні 2025 року продажі суттєво впали.
Вас, як аналітика, просять терміново розібратись:

* **Чому впали продажі?**
* **Що робити: змінювати маркетинг? Перезапускати курси? Вводити знижки?**

### Етап 1: Первинний аналіз даних (EDA)
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('course_sales.csv')
df

df.drop_duplicates(inplace=True) # видаляємо дублікати

df.rename(
    columns={
      'Дата продажу': 'sales_date',
      'Назва курсу': 'name_course',
      'Вартість$': 'cost',
      'Кіл-ть': 'quantity',
      'Всього': 'amount'
         },
    inplace=True
)

df.head()

df.info()

df['sales_date'].unique()

from dateutil.parser import parse

def date_parse(item):
  try:
    return parse(item).strftime('%Y-%m-%d')
  except:
    return None

df.sales_date = df.sales_date.apply(date_parse)

df['sales_date'] = pd.to_datetime(df.sales_date, format='%Y-%m-%d')

start_date = '2023-01-01'
end_date = '2025-05-31'

df = df[(df['sales_date'] >= start_date) & (df['sales_date'] <= end_date)]

df.info()

df['name_course'].unique()

df.name_course.replace({'Python нач': 'python for beginners','Питон для начинающих': 'python for beginners', 'Python For Beginners': 'python for beginners', 'PYTHON-BEGINNERS': 'python for beginners',
                        'DS Boot':'data science bootcamp', 'Data Science BOOTCAMP': 'data science bootcamp', 'Буткемп по Data Science': 'data science bootcamp','Данные.Наука': 'data science bootcamp',
                        'Web-разработка': 'web development', 'Web Dev 101': 'web development', 'веб разработка': 'web development', 'WEB DEVELOPMENT': 'web development', 'web_dev': 'web development',
                        'Machine Learning ADV': 'machine learning advanced', 'ML (уровень 2)':'machine learning advanced', 'машинное обучение+':'machine learning advanced', 'Продвинутый ML':'machine learning advanced',
                        'SQL БАЗОВЫЙ': 'sql crash course', 'Быстрый курс SQL': 'sql crash course', 'sql-cc': 'sql crash course','SQL-Курс': 'sql crash course'}, inplace=True)
df.name_course.unique()

df['name_course'] = df.name_course.astype('category')

df.info()

df['quantity'].unique()

df[(pd.isnull(df['quantity']))]

quantity_calc = df['amount'] / df['cost']
df.quantity.fillna(quantity_calc, inplace=True)

df.info()

"""### Етап 2: Дослідження"""

!pip install ydata-profiling

from ydata_profiling import ProfileReport
profile = ProfileReport(df)
profile.to_file('report.html')

from google.colab import files
files.download('report.html')

df.drop_duplicates(inplace=True) # повторне видалення дублікатів

df.info()

import plotly.graph_objects as go
from plotly.subplots import make_subplots

columns = [
    ('cost', 'Cost Distribution'),
    ('quantity', 'Quantity Distribution'),
    ('amount', 'Amount Distribution'),

]

fig = make_subplots(rows=len(columns),
                    cols=1,
                    shared_xaxes=False,
                    vertical_spacing=0.05,
                    subplot_titles=[title for _, title in columns])

for i, (col, title) in enumerate(columns, start=1):
    fig.add_trace(
        go.Box(x=df[col],
               orientation='h',
               name=title,
               boxmean='sd'),
               row=i,
               col=1
    )

fig.update_layout(
    height=300 * len(columns),
    showlegend=False,
    title_text='Distribution of Courses'
)

import plotly.express as px

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
sns.barplot(data=df, y='name_course', x='amount')
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 6))
sns.barplot(data=df, y='name_course', x='cost')
plt.tight_layout()
plt.show()

# Будуємо гісторраму по сумах продажів
plt.figure(figsize=(10, 6))
plt.hist(df['amount'], bins=20, edgecolor='black')
plt.title("Гістограма суми продажів")
plt.xlabel("Сума продажів")
plt.ylabel("Кількість випадків")
plt.grid(True)
plt.tight_layout()
plt.show()

df.amount.describe()

# Створюємо колонку "month" у форматі YYYY-MM
df['month'] = df['sales_date'].dt.to_period('M')

# Групуємо по місяцях та рахуємо суму продажів
monthly_sales = df.groupby('month')['amount'].sum()

# Виводимо щомісячні продажі (за 3 роки)
print(monthly_sales)

# Рахуємо середньомісячну суму продажів
average_monthly_sales = monthly_sales.median() # медіана, оскільки є викиди
print(f"\nСередньомісячна сума продажів: {average_monthly_sales:.2f}")

monthly_sales.plot(kind='line', marker='o', figsize=(14, 6))
plt.title("Продажі по місяцях")
plt.xlabel("Місяць")
plt.ylabel("Сума продажів")
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

df['month'] = df['sales_date'].dt.month
df['year'] = df['sales_date'].dt.year
pivot = df.pivot_table(index='month', columns='year', values='amount', aggfunc='sum')
sns.heatmap(pivot, annot=True, fmt='.0f')

plt.figure(figsize=(18, 10))
sns.lineplot(data=df, x='sales_date', y='amount', hue='name_course', marker='o')
plt.title('Динаміка продажів для курсів')
plt.xlabel('Місяць')
plt.ylabel('Сума продажів')
plt.xticks(rotation=45)
plt.tight_layout()
plt.legend(title='Курс', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

quantity_course = df.groupby('name_course').agg({
    'quantity': 'sum',
    'amount': 'sum'
})
quantity_course

"""### Етап 3: Висновки

* **Чому насправді впали продажі?**
* **Чи потрібно щось змінювати?**
* **Які рекомендації ви б дали керівництву?**

*** Чому насправді впали продажі?***

Згідно графіку " Продажі по місяцях", теплової карти, та гафіку "Динаміка продажів для курсів" бачимо падіння по сумі продажів з усіх курсів у період з травня по вересень протягом двох років, а також падіння у травні 2025. Це може бути викликано сезонністю, бо на період травень-вересень завжди випадає найбільша кількість відпусток працівників та відповідно, втрата інтересу до придбання навчальних курсів.

***

***Чи потрібно щось змінювати?***
***Які рекомендації ви б дали керівництву?***

Як видно зі зведеної таблиці:
Найбільш популярнимиє курси *machine learning advanced* - 2,8 млн грн та 11,4 тис проданих курсів.
Що говорить про високий попит на дані курси, при найвищий ціні з усіх курсів кількість куплених курсів теж найвища. Але кількість проданих курсів не сильно відрізняється від інших курсів, тому можна інвестувати в рекламу.

Такаж динаміка і у *data science bootcamp* — також високий дохід
2,2 млн грн — друге місце, проданих курсів 11,1 тис - третє місце.
Висока ціна та стабільна кількість покупців, також можна інвестувати в рекламу.

Курс *web development* — стабільний дохід
874 тис. грн — третє місце за доходом серед курсів, при цьому найменша кількість продавжів 10,9 тис. Оптимальне поєднання ціни та кількості.

Курс *python for beginners* — масовий, але дешевий.
Продажі 553 тис. грн — найменше з усіх, а кількість продажів велика 11,1 тис.
Курс надто дешевий, при тому, що має високий попит.
Можливо, варто трохи підняти ціну, щоб збільшити прибуток.

Курс *sql crash course* невеликий дохід, але велика поулярність за продажами - 11,4 тис. Так само як і  *python for beginners* курс надто дешевий, при тому, що має високий попит. Можливо підняти ціну, або зкомбінувати з курсом
 *python for beginners*.
"""